# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpergoMcp < Formula
  desc "MCP server exposing the opergo API to Claude and other MCP clients"
  homepage "https://github.com/Proveder/mcp"
  version "0.1.3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.3/opergo-mcp_0.1.3_darwin_amd64.tar.gz"
      sha256 "e2263ada4617981c9e2d7efa4debb9a64299948f43b93ef404c5d8191c3fa17e"

      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.3/opergo-mcp_0.1.3_darwin_arm64.tar.gz"
      sha256 "2b606bec4b108b0bcdcb596469106e358d0d600aed78053aa4a3b598d3361dbc"

      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.3/opergo-mcp_0.1.3_linux_amd64.tar.gz"
      sha256 "4ea5cb35a69bbc648b347ad599c352316576048363a6c22041d1e22f41a87ff2"
      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.3/opergo-mcp_0.1.3_linux_arm64.tar.gz"
      sha256 "2d5fafad410d16fd3ba11cfa7dd389456172dd527ed6c1be86eca2f3e600176d"
      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      One-time setup:
        opergo-mcp login                    # browser-based Cognito login
        claude mcp add opergo opergo-mcp    # register with Claude Code
        opergo-mcp install-skill            # install the opergo skill (recommended)
    EOS
  end

  test do
    assert_match "opergo-mcp", shell_output("#{bin}/opergo-mcp help 2>&1", 0)
  end
end
