# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpergoMcp < Formula
  desc "MCP server exposing the opergo API to Claude and other MCP clients"
  homepage "https://github.com/Proveder/mcp"
  version "0.1.10"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.10/opergo-mcp_0.1.10_darwin_amd64.tar.gz"
      sha256 "9f329a89bb4e05f5ff9bb0d7fd9cb25e7297cb0f32bf79036f511d64792af4bc"

      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.10/opergo-mcp_0.1.10_darwin_arm64.tar.gz"
      sha256 "485ca988363123b0447d23cedc90a2352cc7f56f6023ec352f5df23b8dd95c3c"

      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.10/opergo-mcp_0.1.10_linux_amd64.tar.gz"
      sha256 "81974d85ea8d1d517a58840c46f64c788c778e531e60399c0d501baf257a4a3d"
      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Proveder/mcp-dist/releases/download/v0.1.10/opergo-mcp_0.1.10_linux_arm64.tar.gz"
      sha256 "e7ac77d9fd8329ac0dfce8ea84482cddb83fcd094bb43dd5a4a2d80fd84ebe23"
      define_method(:install) do
        bin.install "opergo-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      One-time setup:
        opergo-mcp login                    # browser-based Cognito login
        claude mcp add opergo opergo-mcp    # register with Claude Code
        opergo-mcp install-skill            # install the opergo skill (recommended)
    EOS
  end

  test do
    assert_match "opergo-mcp", shell_output("#{bin}/opergo-mcp help 2>&1", 0)
  end
end
